### PR TITLE
Add support for TypeScript

### PR DESCRIPTION
**Pull request by AnandChowdhary**
Hi @mbest, thanks for all your hard work!

This PR adds support for using this package with TypeScript. It adds the declaration file and the `types` key in `package.json`.

### CODE REVIEW

**Comment by mbest** [comment]
Why did you close this?

**Comment by AnandChowdhary** [comment]
I noticed that I wasn't able to use the module in TypeScript regardless of the types, because it's a UMD. The ecosystem has evolved significantly from when you wrote this in 2014, so if you'd be comfortable publishing an ES6 module, it would work perfectly with modern JS compilers, bundlers, and TypeScript. Can I make a PR for that?

**Comment by mbest** [comment]
Sure, that's would be great.

**Comment by mbest** [comment]
Sure, that would be great.

**Pull request closed without merging**
